# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/cgshop2021/',
                'doc_host': 'https://ocker11.github.io',
                'git_url': 'https://github.com/ocker11/cgshop2021/tree/master/',
                'lib_path': 'cgshop2021'},
  'syms': { 'cgshop2021.core': { 'cgshop2021.core.say_hello': ( 'https://ocker11.github.io/cgshop2021/core.html#say_hello',
                                                                'https://github.com/ocker11/cgshop2021/tree/master//blob/master/cgshop2021/core.py#L7')}}}